using FluentAssertions;
using S7evemetry.F1_2020.Helpers;
using Xunit;

namespace S7evemetry.Tests.F1_2020.Helpers
{
    public class DriverHelperTests
    {
        [Theory]
        [InlineData(0, "Carlos Sainz")]
        [InlineData(1, "Daniil Kvyat")]
        [InlineData(2, "Daniel Ricciardo")]
        [InlineData(6, "Kimi Räikkönen")]
        [InlineData(7, "Lewis Hamilton")]
        [InlineData(9, "Max Verstappen")]
        [InlineData(10, "Nico Hulkenburg")]
        [InlineData(11, "Kevin Magnussen")]
        [InlineData(12, "Romain Grosjean")]
        [InlineData(13, "Sebastian Vettel")]
        [InlineData(14, "Sergio Perez")]
        [InlineData(15, "Valtteri Bottas")]
        [InlineData(17, "Esteban Ocon")]
        [InlineData(19, "Lance Stroll")]
        [InlineData(20, "Arron Barnes")]
        [InlineData(21, "Martin Giles")]
        [InlineData(22, "Alex Murray")]
        [InlineData(23, "Lucas Roth")]
        [InlineData(24, "Igor Correia")]
        [InlineData(25, "Sophie Levasseur")]
        [InlineData(26, "Jonas Schiffer")]
        [InlineData(27, "Alain Forest")]
        [InlineData(28, "Jay Letourneau")]
        [InlineData(29, "Esto Saari")]
        [InlineData(30, "Yasar Atiyeh")]
        [InlineData(31, "Callisto Calabresi")]
        [InlineData(32, "Naota Izum")]
        [InlineData(33, "Howard Clarke")]
        [InlineData(34, "Wilheim Kaufmann")]
        [InlineData(35, "Marie Laursen")]
        [InlineData(36, "Flavio Nieves")]
        [InlineData(37, "Peter Belousov")]
        [InlineData(38, "Klimek Michalski")]
        [InlineData(39, "Santiago Moreno")]
        [InlineData(40, "Benjamin Coppens")]
        [InlineData(41, "Noah Visser")]
        [InlineData(42, "Gert Waldmuller")]
        [InlineData(43, "Julian Quesada")]
        [InlineData(44, "Daniel Jones")]
        [InlineData(45, "Artem Markelov")]
        [InlineData(46, "Tadasuke Makino")]
        [InlineData(47, "Sean Gelael")]
        [InlineData(48, "Nyck De Vries")]
        [InlineData(49, "Jack Aitken")]
        [InlineData(50, "George Russell")]
        [InlineData(51, "Maximilian Günther")]
        [InlineData(52, "Nirei Fukuzumi")]
        [InlineData(53, "Luca Ghiotto")]
        [InlineData(54, "Lando Norris")]
        [InlineData(55, "Sérgio Sette Câmara")]
        [InlineData(56, "Louis Delétraz")]
        [InlineData(57, "Antonio Fuoco")]
        [InlineData(58, "Charles Leclerc")]
        [InlineData(59, "Pierre Gasly")]
        [InlineData(62, "Alexander Albon")]
        [InlineData(63, "Nicholas Latifi")]
        [InlineData(64, "Dorian Boccolacci")]
        [InlineData(65, "Niko Kari")]
        [InlineData(66, "Roberto Merhi")]
        [InlineData(67, "Arjun Maini")]
        [InlineData(68, "Alessio Lorandi")]
        [InlineData(69, "Ruben Meijer")]
        [InlineData(70, "Rashid Nair")]
        [InlineData(71, "Jack Tremblay")]
        [InlineData(74, "Antonio Giovinazzi")]
        [InlineData(75, "Robert Kubica")]
        [InlineData(78, "Nobuharu Matsushita")]
        [InlineData(79, "Nikita Mazepin")]
        [InlineData(80, "Guanya Zhou")]
        [InlineData(81, "Mick Schumacher")]
        [InlineData(82, "Callum Ilott")]
        [InlineData(83, "Juan Manuel Correa")]
        [InlineData(84, "Jordan King")]
        [InlineData(85, "Mahaveer Raghunathan")]
        [InlineData(86, "Tatiana Calderon")]
        [InlineData(87, "Anthoine Hubert")]
        [InlineData(88, "Guiliano Alesi")]
        [InlineData(89, "Ralph Boschung")]
        [InlineData(855, "Unknown")]
        public void DriverHelperTest(int id, string expected)
        {
            var result = DriverHelper.GetDriverById(id);
            result.Should().Be(expected);
        }
    }
}
